stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Dummy Content" > build_output.txt
  artifacts:
    paths:
      - build_output.txt

test-job:
  stage: test
  dependencies:
    - build-job
  script:
    - cat build_output.txt
